# Generated by Django 5.0.1 on 2024-01-27 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fatigue_factor', models.IntegerField()),
                ('primary_bodyparts', models.ManyToManyField(related_name='primary_bodyparts', to='trainer.bodypart')),
                ('secondary_bodyparts', models.ManyToManyField(related_name='secondary_bodyparts', to='trainer.bodypart')),
            ],
        ),
        migrations.CreateModel(
            name='IntensityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.user')),
            ],
        ),
        migrations.CreateModel(
            name='Intensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('percentage1RM', models.DecimalField(decimal_places=2, max_digits=4)),
                ('intensityTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.intensitytable')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reps', models.IntegerField()),
                ('rir', models.IntegerField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.exercise')),
                ('setGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.setgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='Start time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.user')),
            ],
        ),
        migrations.AddField(
            model_name='setgroup',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.workout'),
        ),
    ]
