# Generated by Django 5.0.1 on 2024-03-18 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisefamily',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ExerciseFamilySharedWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.exercisefamily')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercisefamily',
            name='shared_with',
            field=models.ManyToManyField(related_name='exercise_family_shared_with', through='trainer.ExerciseFamilySharedWith', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='exercisefamily',
            constraint=models.UniqueConstraint(fields=('name', 'created_by'), name='unique_name_created_by_combination_exercise_family'),
        ),
    ]
