# Generated by Django 5.0.2 on 2024-02-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_rename_lifter_intensitytable_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='bodyweight',
            field=models.FloatField(default=80.0),
        ),
    ]
