# Generated by Django 5.0.1 on 2024-03-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_exercise_bodyweight_inclusion_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='bodyweight_inclusion_factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
