# Generated by Django 5.0.1 on 2024-03-26 23:20

from django.db import migrations, models

def populate_number_within_workout(apps, schema_editor):
    Workout = apps.get_model('trainer', 'Workout')
    ExerciseSet = apps.get_model('trainer', 'ExerciseSet')
    for workout in Workout.objects.all():
        exercise_sets = ExerciseSet.objects.filter(workout=workout).order_by('id')
        for index, exercise_set in enumerate(exercise_sets):
            exercise_set.number_within_workout = index
            exercise_set.save()


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_alter_exercise_bodyweight_inclusion_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='number_within_workout',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.RunPython(populate_number_within_workout),
    ]
